(function() {var implementors = {};
implementors["release_manager"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">IOError</a>&gt; for <a class=\"enum\" href=\"release_manager/enum.Error.html\" title=\"enum release_manager::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/toml/0.4/toml/de/struct.Error.html\" title=\"struct toml::de::Error\">TomlReadError</a>&gt; for <a class=\"enum\" href=\"release_manager/enum.Error.html\" title=\"enum release_manager::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://docs.rs/toml/0.4/toml/ser/enum.Error.html\" title=\"enum toml::ser::Error\">TomlWriteError</a>&gt; for <a class=\"enum\" href=\"release_manager/enum.Error.html\" title=\"enum release_manager::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;ZipError&gt; for <a class=\"enum\" href=\"release_manager/enum.Error.html\" title=\"enum release_manager::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.StripPrefixError.html\" title=\"struct std::path::StripPrefixError\">StripPrefixError</a>&gt; for <a class=\"enum\" href=\"release_manager/enum.Error.html\" title=\"enum release_manager::Error\">Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
